### ISSUE TITLE
[Bug]: Transitive dependencies of 1st party deps referenced from `npm_link_package` are not available for `js_run_binary` targets

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_js#1109]
### What happened?

When referencing 1st party dependencies defined by `npm_link_package`, a `js_run_binary` target does not have access to that dependency's transitive dependencies.

For example:

```
package-0
  - depends on 'lodash'

package-1
  - depends on '//:node_modules/package-0' (an 'npm_link_package' target to 'package-0')
```

Abridged output from reproduction repository: https://github.com/gregjacobs/rules-js-transitive-deps

```
$ bazel build //package-1:generate_uppercase_txt

...

Error: Cannot find module 'lodash'
```

When running the underlying `js_binary` directly (in conjunction with `bazel run` instead of `bazel build`), transitive dependencies are available.

### Version

Development (host) and target OS/architectures: Reproducible on both **MacOS Big Sur (11.7.7)** and **MacOS Monterey (12.6.3)**

Output of `bazel --version`: **bazel 6.2.1**

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: **rules_js@1.27.1, rules_ts@1.3.3**

Language(s) and/or frameworks involved: JavaScript/TypeScript

### How to reproduce

Reproduction repository: https://github.com/gregjacobs/rules-js-transitive-deps

Check for instructions in readme.md

**Comment by gregmagolan** [comment]
At a quick glance, I think the issue is you're dropping the transitive deps when you pass the `:library` ts_project target to js_library `srcs` instead of `deps`. https://github.com/gregjacobs/rules-js-transitive-deps/blob/25c423b8f33a7508439808422222bb32a54e757e/package-1/BUILD#L34.

It should work if you go through `deps` tho I haven't tried it yet.

**Comment by gregmagolan** [comment]
In general `srcs` are direct source files for that target, `deps` are other targets who's outputs that target depends on transitively, and `data` is files that should be included in the runfiles of downstream `*_binary` and `*_test` targets.

For most things rules_js rules are forgiving if you add a dep to `srcs` instead of `deps` but the transitive npm deps that are linked when a downstream `npm_package` is linked only looks at `deps` and data`. These are named "npm package store deps" in the code: https://github.com/aspect-build/rules_js/blob/cd2e87770e265158686dc53086bbf04965b2e4f9/js/private/js_library.bzl#L197

Looking at this however, I think those could be changed to includes `srcs` like so:
```
    npm_package_store_deps = gather_npm_package_store_deps(
        targets = ctx.attr.data + ctx.attr.deps + ctx.attr.srcs,
    )
```

so js_library is more forgiving in this case

**Comment by gregmagolan** [comment]
FYI @jbedard

**Comment by gregjacobs** [comment]
Gotcha, thanks for that. This info would definitely be a great addition to the docs for other JS devs coming into Bazel. I think most devs new to the ecosystem won't necessarily understand the internals talked about in the `js_library` docs as they are right now, so having some general advice like the above in the docs' attributes tables would definitely be helpful.
