### ISSUE TITLE
[FR]: Remove need for `npm_link_all_packages` in BUILD files

### ISSUE THREAD

**Issue by UebelAndre** [aspect-build/rules_js#1128]
### What is the current behavior?

Any repository which uses `rules_js` is seemingly require to add `npm_link_all_packages(name = "node_modules")` in the root BUILD file. This creates a requirement that that repository's `npm_translate_lock` repository to be defined. This makes loading the repo difficult in some cases where some teams don't want any javascript dependencies in their projects.

### Describe the feature

Dependencies shouldn't need to be aliased in the repo, in addition to adding lots of noise to `bazel query` commands, it makes loading repositories harder. Any reference to `:node_modules` in the packages should instead be referable via the `npm_translate_lock` repository. E.g. `//:node_modules` would become `@npm//:node_modules` or maybe `@npm//<repo_name>:node_modules` if there's conflicts in the root of that repository.

**Comment by alexeagle** [comment]
This is a fundamental design decision in rules_js. The Node.js interpreter simply requires that dependencies appear in the source tree. To make Bazel compatible with that, we take the tradeoff where the ergonomics are impaired in the way you describe, and in exchange, nodejs resolution works.

rules_nodejs is the repo that takes the other approach of leaving npm depnedencies in an external repo, however many nodejs programs don't work, despite tricky monkey-patching of the `require` function. Generally that's because they re-implement the canonical nodejs resolution algorithm themselves.

We don't think it's possible to have it both ways - to follow idiomatic Bazel layout of third-party deps and still have that work with Node.

**Comment by gregmagolan** [comment]
Some background on rules_js design can be found here: https://docs.aspect.build/rules/aspect_rules_js#design

In short, node wants to resolve npm deps with standard node_modules resolution and with rules_js we wanted to allow for idiomatic npm dep resolution as opposed to patching require which is what rules_nodejs did and what yarn PnP does, for example. rules_nodejs also had a hybrid "lay out node_modules at runtime in the action" but that approach had many flaws that I won't get into here.

You don't, however, require an `npm_link_all_packages` in the root BUILD file. If you don't want to require all developers to have `npm_translate_lock` defined, you can simply move your package.json and pnpm-lock file to a sub-directory in your repository and `npm_link_all_packages` will only be required there (where the virtual store is created). If there are other subdirectory trees which require `node_modules` then they can be added to the pnpm workspace with relative `../other-subdir` paths.
