### ISSUE TITLE
[Bug]: js_run_devserver should produce a .bat file on Windows

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_js#1131]
### What happened?

Running the devserver target produces an error like `entry_point not found`, see screenshot from Windows:

![Screenshot 2023-06-28 at 9 30 48 AM](https://github.com/aspect-build/rules_js/assets/47395/5c2a8b0d-1202-4e9f-b305-fba97c810fff)

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.2.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: aspect_rules_js 1.26.1

### How to reproduce

```shell
A simple example with an http-server is enough to cause this.
```

**Comment by gregmagolan** [comment]
With https://github.com/aspect-build/rules_js/pull/1156 this should work using the `command` entry point for `js_run_devserver` with the `bins` feature of `npm_translate_lock`.

The trouble with the `http_server_bin.http_server_binary(name = "http_server")` approach on Windows is that this method relies on the `bin` of the npm package to be executable, which it typically is a linux/darwin since it is typically an executable file with `#!/usr/bin/env node`. This is true for `http-server`. On Windows, the `bin` can't be used directly but must instead be used via the generated `node_modules/.bin/http-server.cmd` file that yarn, npm & pnpm all create.

#1156 adds the functionality to create `node_modules/.bin/http-server.cmd` and `js_run_devserver` already has the ability to run an arbitrary command with `command`. So the wiring would look like so:

```
npm_translate_lock(
    name = "npm",
    bins = {
        # derived from "bin" attribute in node_modules/http-server/package.json
        "http-server": {
            "http-server": "./bin/http-server",
        },
    },
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
```

```
js_run_devserver(
    name = "devserver_alt",
    chdir = package_name(),
    command = "../node_modules/.bin/http-server.cmd",
    data = [
        ":http_root",
        ":web_files",
        "//:node_modules/http-server",
    ],
    env = {"BAZEL_BINDIR": "."},
    log_level = "debug",
)
```

in rules_js e2e/js_run_devserver: https://github.com/aspect-build/rules_js/blob/main/e2e/js_run_devserver/src/BUILD.bazel#L55. The `command` path will be the relative path from the Bazel package the target is in to where the `node_modules` folder is.

**Comment by gregmagolan** [comment]
An alternate approach could be to patch the `http-server` npm package and add a `http-server.cmd` file and a `http-server-win` alternate entry point to its `bins` and then wire it up with:

```
load("@npm//:http-server/package_json.bzl", http_server_bin = "bin")

http_server_bin.http_server_win_binary(
    name = "http_server_win",
)

js_run_devserver(
    name = "devserver",
    chdir = package_name(),
    data = [":web_files"],
    log_level = "debug",
    tool = ":http_server_win",
)
```

... this seems more difficult and more confusing to me.
