### ISSUE TITLE
v1.0.0-rc.0 fails to fetch https://registry.npmjs.org/bl/-/bl-4.0.3.tgz

### ISSUE THREAD

**Issue by lummax** [aspect-build/rules_js#261]
With `v1.0.0-rc.0` while pulling `bl/4.0.3` I get the following error:

```
ERROR: /home/XXX/repos/XXX/projects/support/icon-converter/BUILD.bazel:3:22: //projects/support/icon-converter:.aspect_rules_js/node_modules/bl/4.0.3/pkg depends on @npm__bl__4.0.3//:source_directory in repository @npm__bl__4.0.3 which failed to fetch. no such package '@npm__bl__4.0.3//': at offset 773, object has duplicate key: "license"
ERROR: Analysis of target '//projects/support/icon-converter:icon-converter' failed; build aborted: 
INFO: Elapsed time: 0.252s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
```

Inspecting the `package.json` from https://registry.npmjs.org/bl/-/bl-4.0.3.tgz shows the following with is of course broken.

```json
{
  "name": "bl",
  "version": "4.0.3",
  "description": "Buffer List: collect buffers and access with a standard readable Buffer interface, streamable too!",
  "license": "MIT",
  "main": "bl.js",
...
  "license": "MIT",
...
}
```

This malformed `package.json` was fixed with https://github.com/rvagg/bl/blob/v4.0.4/package.json

`yarn2` handles this fine.

**Comment by gregmagolan** [comment]
This is the same issue seen here, https://github.com/aspect-build/rules_js/issues/148 where the underlying problem is json.decode is too strict and fails on duplicate keys. @alexeagle filed an issue with Bazel here: https://github.com/bazelbuild/bazel/issues/15605.

Until that is fixed, you'll have to patch the package.json of any offending packages in npm_translate_lock (for example, https://github.com/aspect-build/rules_js/issues/148#issuecomment-1144378565) or update to the version that has the duplicate keys fixed.

**Comment by lummax** [comment]
:+1: I am an idiot for not checking the issue history properly.

Thank you :)
