### ISSUE TITLE
node patches are not applied when the entry point is a mjs file

### ISSUE THREAD

**Issue by jbedard** [aspect-build/rules_js#341]
When the entry point is a mjs file the node patches are not applied correctly. It seems `--preserve-symlinks-main` fixes it which should potentially be enabled by default.

~~The js entry_point file requires preserving the symlink just like any other symlinked file in the sandbox. `--preserve-symlinks-main` should be enabled for all launched node processes just like `--preserve-symlinks`~~.

https://nodejs.org/api/cli.html#--preserve-symlinks-main (added in node v10.2.0)

**Comment by gregmagolan** [comment]
don't want `--preserve-symlinks` on as it breaks node_modules resolution in rules_js; the symlink guards keep processes in the sandbox and their runfiles. but the `--preserve-symlinks-main` option on by default might be correct since `.mjs` entry points skirt around the symlink guards and leave the sandbox currently
