### ISSUE TITLE
`node-gyp rebuild` fails while running the lifecycle hooks for package aws-lambda-ric

### ISSUE THREAD

**Issue by bhavitsharma** [aspect-build/rules_js#386]
Installing the package `aws-lambda-ric@2.0.0` fails when its postinstall script runs the script `node-gyp rebuild`. 
The error is:

```
 File "/home/devbox/.cache/bazel/_bazel_devbox/d1bf528b9e29083fb94e8c7ce57bbdd1/sandbox/linux-sandbox/1633/execroot/relicx/bazel-out/k8-fastbuild/bin/ts/no
de_modules/.aspect_rules_js/node-gyp@8.1.0/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 749, in Write
    self.fp = open(output_filename, "w")
FileNotFoundError: [Errno 2] No such file or directory: './build/../../../../../../../../../../../../../../execroot/relicx/bazel-out/k8-fastbuild/bin/ts/nod
e_modules/.aspect_rules_js/node-addon-api@3.2.1/node_modules/node-addon-api/nothing.target.mk'
```

The installation works fine for other packages dependent on `node-gyp`. 
Manually running `pnpm install` correctly installs the packages.
I can't use `lifecycle_hooks_exclude` since we have a run-time dependency on this package.
I would appreciate any help!

**Comment by bhavitsharma** [comment]
https://github.com/aws/aws-lambda-nodejs-runtime-interface-client
aws-lambda-ric

**Comment by gregmagolan** [comment]
Can you try setting the execution requirements for that lifecycle hook so it runs out of the sandbox? The path in the error message is suspicious.

In you `npm_translate_lock`, you can configure this for a specific package by name or name@version,

```
    lifecycle_hooks_execution_requirements = {
        "aws-lambda-ric": ["no-sandbox"],
    },
```

```
    lifecycle_hooks_execution_requirements = {
        "aws-lambda-ric@2.0.0": ["no-sandbox"],
    },
```

or for all packages,

```
    lifecycle_hooks_execution_requirements = {
        "*": ["no-sandbox"],
    },
```

**Comment by bhavitsharma** [comment]
Wow, This worked. Thanks a lot, @gregmagolan, for your prompt response! Appreciate it.
Two questions:
1. Can the `no-sandbox` have undesired effects while running other ts builds in sandbox mode? 
2. What will help more to debug this issue more? Reproduction is simple - just add `aws-lambda-ric:2.0.0` as a dependency. Is this because `aws-lambda-ric` package is trying to write some files outside its sandbox directory? The error above shows it's trying to write a file inside another package (a temp file).

**Comment by gregmagolan** [comment]
Running lifecycle hooks outside of the sandbox might be a better default actually, both for preventing failures such as this and for performance since sandboxed actions have to copy their results out of the sandbox when they are done.

Some lc hooks might end up writing some files to other packages (they shouldn't do this) but it shouldn't break anything if they do. When lc hooks run outside of bazel in yarn, npm and pnpm they are never sandboxed.

As far a debugging goes, you analysis sounds correct with some tool trying to write to a write-protected location outside of the sandbox. The sandbox looks like a symlink far to tools so it is common for tools to follow symlinks and escape.

**Comment by gregmagolan** [comment]
Flipped the default to run lc hooks with no sandbox in https://github.com/aspect-build/rules_js/commit/72c9f2d92f91cfbd00302fd1790d4d5caf672c26
