### ISSUE TITLE
Incompatible toolchain on M1

### ISSUE THREAD

**Issue by arohner** [aspect-build/rules_js#469]
Using Bazel 5.3.1 and rules_js 1.3.1 on an M1 MBP, I get:

```
While resolving toolchains for target //design-system:_components__js_binary: no matching toolchains found for types @rules_nodejs//nodejs:toolchain_type
```

Using `--toolchain_resolution_debug=@rules_nodejs//nodejs:toolchain_type`

```
 Rejected toolchain @nodejs_darwin_arm64//:node_toolchain; mismatching values: aarch64
```

I have an existing platform definition:

```
    constraint_values = [
        "@platforms//os:osx",
        "@platforms//cpu:arm64",
        "@bazel_tools//tools/cpp:clang"])
```

Which works for C++ and Java code. If I change the CPU from `arm64` to `aarch64`, node targets start compiling, but C++ targets do not.

**Comment by alexeagle** [comment]
rules_js gets the toolchain from rules_nodejs:
https://github.com/bazelbuild/rules_nodejs/blob/43159a5b5b2c5a7027b7d062e9d75025c1e65acd/nodejs/private/toolchains_repo.bzl#L54

Now, what's the difference between aarch64 and arm64?
Apparently it's just an alias: https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD#L16-L20

So I think the real bug here is that the toolchain resolution didn't allow for aliased `constraint_value`.
As a workaround I imagine you can patch that line in rules_nodejs in your `http_archive` where you fetch it.

Perhaps the right fix is just to change rules_nodejs to use `arm64` rather than `aarch64`. I can't predict whether that might cause some other problem. We might want to ask someone on the Bazel team who's more expert on that.

**Comment by alexeagle** [comment]
@brentleyjones you've touched aarch64 vs. arm64 in Bazel recently, could you give guidance about whether rules_nodejs ought to just change them all like you did in https://github.com/bazelbuild/bazel/pull/14995/files ?

**Comment by alexeagle** [comment]
Yeah, I see now, @thii introduced the alias in https://github.com/bazelbuild/platforms/commit/e20c93258af20dfd452b93c6617bedd0bc5f9359

**Comment by xinbinhuang** [comment]
@alexeagle  I just got into a similar issue, but the self-detected cpu is `@platforms//cpu:aarch64` instead of `@platforms//cpu:arm64`. The issue seems to be that the installed `@platforms` is outdated before the alias was introduced
```
> cat bazel-out/../../../external/platforms/cpu/BUILD

...
constraint_value(
    name = "aarch64",
    constraint_setting = ":cpu",
)
...
```

So I think a better fix is to pull in a up-to-date `@platforms` in `WORKSPACE`. Adding this fix the issue for me

```bazel
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "platforms",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/platforms/releases/download/0.0.6/platforms-0.0.6.tar.gz",
        "https://github.com/bazelbuild/platforms/releases/download/0.0.6/platforms-0.0.6.tar.gz",
    ],
    sha256 = "5308fc1d8865406a49427ba24a9ab53087f17f5266a7aabbfc28823f3916e1ca",
)
```
