### ISSUE TITLE
[Bug]: Prettier not working with rules_js

### ISSUE THREAD

**Issue by guillaumep** [aspect-build/rules_js#639]
### What happened?

Prettier puts every file in error when ran through Bazel, event though it works when running using pnpm. See reproduction steps below.

### Version

Development (host) and target OS/architectures: Debian testing / AMD Ryzen 9

Output of `bazel --version`: bazel 5.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: see reproduction depo below

Language(s) and/or frameworks involved: rules_js

### How to reproduce

```shell
git clone https://github.com/guillaumep/bazel-examples.git
cd bazel-examples/vue
git checkout prettier_test
bazel test :prettier
```

Expected: test passes.
Actual: Prettier put every file in error.

To test Prettier using pnpm:

```
nvm install 16
nvm use 16
corepack enable
pnpm install
pnpm exec prettier --check src
```

**Comment by supercairos** [comment]
Is this due to the hoisting pattern ?

Try hoisting it ?

**Comment by guillaumep** [comment]
> Is this due to the hoisting pattern ?
> Try hoisting it ?

`hoist=false` is properly set in `.npmrc` as recommended in the documentation.

**Comment by supercairos** [comment]
I personnaly use prettier via eslint and a specific eslint rule and have no issues

**Comment by alexeagle** [comment]
Running the formatter as a Bazel action or test is kinda wasteful, since a formatter doesn't need to know about the dependency graph, and a version control integration like pre-commit.com is more appropriate for deciding which touched files to re-format.

It's useful to have Bazel manage the toolchain so you know what version of node/prettier is being used, we have https://github.com/aspect-build/bazel-super-formatter for that.

Of course you can decide differently and use any npm program you like. What does the error from prettier look like?

**Comment by guillaumep** [comment]
@alexeagle The error is as follow:

```
==================== Test output for //:prettier:
Checking formatting...
[warn] src/App.vue
[warn] src/assets/base.css
[warn] src/components/TheWelcome.vue
[warn] src/components/WelcomeItem.vue
[warn] src/main.ts
[warn] src/router/index.ts
[warn] src/views/HomeView.vue
[warn] Code style issues found in 7 files. Forgot to run Prettier?
================================================================================
```

**Comment by matthewjh** [comment]
FWIW we run prettier in check mode as a bazel test so we get incrementality and caching, which is useful since prettier isn't the fastest. We use it with rules_js without issue. 

Is there a verbose mode that you can run prettier in that will show you why it thinks those files arent correctly formatted? It would be interesting to find out why it thinks they aren't.

**Comment by alexeagle** [comment]
Check out the super-formatter README - it's incremental/scalable using the low-tech solution everyone outside bazel-land uses: just format the changed files. super-formatter is really "just another formatter" which happens to support many languages. It's best to use with something like pre-commit.com in your dev workflows.

**Comment by matthewjh** [comment]
Yes, commit hooks cover formatting incrementally, but bazel test handles checking/verification incrementally. They are addressing different problems. You're talking about formatting.

**Comment by alexeagle** [comment]
For checking, you'd also want to check just the changed files, pre-commit.ci is an example of how to do that.

Bazel can be made to work, but since there's me dependency graph it just feels like overkill, plus you have to include all files as inputs and no one wants to hand-maintain some filegroup-like rules to include all their markdown for example.

**Comment by guillaumep** [comment]
> Is there a verbose mode that you can run prettier in that will show you why it thinks those files arent correctly formatted? It would be interesting to find out why it thinks they aren't.

I've looked at [Prettier's documentation](https://prettier.io/docs/en/cli.html) to try to find a debug switch before opening this issue in order to try to understand what's happening. Unfortunately there does not seems to have an option that would help, or if such an option exists I did not find it.

**Comment by guillaumep** [comment]
I'll take the initiative to close the issue. Please reopen if needed. See above comments.
